Healthchecks to ensure django container kicks off only after db container is healthy.
openkilt/openrepo pull request #23
Opened 2024-08-12 16:21 UTC by radhaksri

Prior to this proposed fix, django container kicks off as soon as the db container is created. This ends up in these errors on the django container startup as shown in the attached file. 

[all_containers_launch.log](https://github.com/user-attachments/files/16589464/all_containers_launch.log)

The proposed fix implements a health check that uses pg_isready to establish that postgres db is indeed ready, and for the django container to wait for db container to be healthy before kicking off migrations.

2024-08-12 16:31 UTC, radhaksri commented
@inistor, @matthill, @denisgolius, @k0ste : Created this PR to let django container start only after db container is healthy. Please review and merge as you see fit!

2024-08-13 04:57 UTC, inistor requested changes

2024-08-13 04:57 UTC, inistor commented on docker-compose.yml
>        - "django"
If I understand the architecture correctly, the `worker` container depends directly on the DB, not on `django` - so its `depends_on` directive should be similar to `django`'s.

2024-08-13 04:57 UTC, inistor commented on docker-compose.yml
> -
Pedantic: this PR should only perform changes related to its purpose, omitting styling or typos - it's easier to follow

2024-08-13 04:57 UTC, inistor commented on docker-compose.yml
> -version: "3.9"
Pedantic: this PR should only perform changes related to its purpose, omitting styling or typos - it's easier to follow

2024-08-13 04:57 UTC, inistor commented on docker-compose.yml
> +      retries: 5
A simpler healthcheck directive might be better:
```
    healthcheck:
        test: pg_isready
        interval: 5s
```
See [this PR](https://github.com/docker-library/docs/pull/2393/files).

2026-06-17 19:52 UTC, matthill commented
Added health checks for all services on https://github.com/openkilt/openrepo/tree/release/v1.1.0

2026-06-17 19:52 UTC, closed without merging